export const START_APPLICATION = 'START_APPLICATION';
export const CONFIG_LOADED = 'CONFIG_LOADED';
export const SUBMIT_TRIGGER = 'SUBMIT_TRIGGER';
export const RENDER_BADGE = 'RENDER_BADGE';
export const RENDER_NEG_BADGE = 'RENDER_NEG_BADGE';
export const EXCUSE_TRIGGER = 'EXCUSE_TRIGGER';